services:
  nuero_proxy:
    build: .
    entrypoint: ["python", "main.py"]
    container_name: nuero_proxy
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "8001:6379"
    container_name: redis